spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vk_sponsor_block
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db-migrations/changelog.yaml

jwt:
  subject: User Details
  secret: JWT_SECRET
  issuer: vksponsorblock
  user-id-claim: userId
  username-claim: username
